### ISSUE TITLE
Regarding your jdtls configuration

### ISSUE THREAD

**Issue by ghost** [PlatyPew/dotfiles#2]
Hi I'm setting up again neovim for java development again and I was looking at your dotfiles.
Do you use nvim-jdtls only for dap ? I can't find any actual nvim-jdtls setup except for:
https://github.com/PlatyPew/dotfiles/blob/5fb048411c8830c13481b469fa847128d76f9446/configs/neovim/lua/config/lsp.lua#L60 ( I think )
Do you use neovim for java projects ? If you have time could you please go into detail about what files I should look at and what generally you wanted from a nvim java environment ?

**Comment by PlatyPew** [comment]
Yes these are mainly for DAP, however, I use lsp-installer for jdtls autocompletion

https://github.com/PlatyPew/dotfiles/blob/10ea00d90ffae05191d72c2e6d4b33647011ca61/configs/neovim/lua/config/lsp.lua#L34-L36

https://github.com/PlatyPew/dotfiles/blob/10ea00d90ffae05191d72c2e6d4b33647011ca61/configs/neovim/lua/config/lsp.lua#L53-L62

**Comment by ghost** [comment]
`extendedCapabilities = require("jdtls").extendedClientCapabilities,`
I see thank you. Could you please pinpoint me towards a resource that explains what this does exactly ? I saw it on a few github issues and in a few  dotfile repos.
